
outboundclients:
  starling:
    core:
      baseurl: https://api-sandbox.starlingbank.com
      accesstoken: eyJhbGciOiJQUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_21Ty47bMAz8lcLn5cKvKHZuvfUH-gE0SSfC2pIhydkuiv575ciJ42APATwz5JAUmb-Z9j47ZThpYBntuw_oBm3OHZqPd7Jj9pb5uYsRBcuhLHuGrqUO6iPn0FaUAxMW3aGsWbUSg-XPlJ2KY17FX9OWb5nGkIi8qeuFQCI7m_DLDizut-bVu1HtEaqcD1BXbaxSdwUUhVK55LlQT9E72A8xWwYKEih1wCXjCC03CvK2KJpa1WVR9TEjjvWTSLzfslqsFFSqVFAz1oBFTnBQVOYN9qo5HJeByU6yPErqFC63VsHgKCcnyD9ehPA1vQiaxQTda3F7ftA-7JgVMLvY5ElYhwdISghIl1EekXO4WKd93BBow_qqecYhaR0OaGjthNAxkDXB2SH5LsyqWdNrN2LQ1oDtoZ8Nr_Vo9sGO97ZlRL1mj2gYg5xYBgnygLewUQJGhCeKcBHv-JY54ZfIXUpgNUlgCwI94nn1TNr2CcGh8UhLzw8aBktx-s07EWCXZ3hl1yxnez3cS6XaO-oW5YRET2EH_F76dDq6e7zGVXg4262PHbeOuuNuPs9MGq6Pz_6NxSZ-47WJyZQuwvMgDHHs7Wq8hBAHnKcVTng_k_h3j1cUj8k6fiq_Z-919-w3-WA_zYMPsjQA5K-v1MR9op53elvF65Kzf_8BCCJtSaEEAAA.Y0U6UpsRhdy0jnFkqjU2NE9YZ1aj--KodoSr1B2HiFmKfg8UOoA6DzAv0HHhMMxK0PBktaXQhOkyZ-HoAZ7fhEEH6NOSvnxngfwe9lGBlCf09LOzp_IXtEqEfrXXkiRKUhA-vD7euNbbHb_IY1RRaVmQntJtZWO4yyhxjaZMyRrkOHQPPAX7mdqushLMnujLmisDLQc4zkyq-W2O4W5CQkyuQVA-82xjMlWNhbnPO9c_Wmk6N1to0Cr3WiENwHAvF4EDEyzTOFbAGmTK-22dXi-GgeIBdFFdY_yjGQ-5qFAo3ckb2ZNxP7mj3hkf8v8vFs3OgKcX3WoxyWfh2H7zAEfvLzhLfQL19KS3jVon9p4JL7OxGtpITF1VxvO8OEL-sjAdRMYfgp1dvEDh67_u_xyividLPW-JhBpzFP3kkfwzEFmhz8JxSBmyU4oY_2Ug1lFmOUeKJSGXBMIZYs5ucJF4g80vI7iTsQg88zr_yienXMqQB7HCwBiOb6ZVc1BaZCSU-CRs3Mnowp0bwEy-G7fbzmyzCRINGeMifNw_VNfru4HuVpsjxN75JOflP6KTtkCwQkK6qo59_6-bFA-U5J6sVlF-725_eZKUgn83_68edgSepOlNIDy9jMiIUKEENt8FswUhP3PQbsQlkF0ri9rAyXqYP532RcOsJM_amEA
    accounts:
      listaccnums:
        verb: GET
        resource: /api/v2/accounts
      confirmationoffunds:
        verb: GET
        resource: /api/v2/accounts/{accountUid}/confirmation-of-funds
    transactionfeed:
      getsettledinrange:
        verb: GET
        resource: /api/v2/feed/account/{accountUid}/settled-transactions-between
    savingsgoals:
      get:
        verb: GET
        resource: /api/v2/account/{accountUid}/savings-goals
      create:
        verb: PUT
        resource: /api/v2/account/{accountUid}/savings-goals
      transfer:
        verb: PUT
        resource: /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}/add-money/{transferUid}