
outboundclients:
  starling:
    core:
      baseurl: https://api-sandbox.starlingbank.com
      accesstoken: eyJhbGciOiJQUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_21Ty5KjMAz8lS3OoyleGQO3ve0P7AcIS05cAzZlm8xObe2_r8EkhFRyorullmQpfzPtfdZlOGkgHu27D-gGbc49ms93acfsLfNzHyPyUjLXUkItlYAaixYaUTRQl0XZl5wrpcoYzH-mrCtEXuVCiKp8yzSGlSjbtqgWAqW0swm_7EDsfmvavEWFJTQSKRZoCuiJGiCkRrAipjaP3sF-skkZhaD6o81bIPFRQc2thL6vCuBK5Bh_fcUYM-JYP6Vk7_c6qs6je1P1sQ7l0JflCZQ4NadClGXRFMvA0k68PErqFC5rq2Bw5M4x0o8nIXxPT4ImNkErze7ID9qHA7MBIheb7Jh0uIOkhIDyMvI9cg4X67SPGwJtSF81zTgkrccBjdw6kegIpDXB2SH5LsymWaO0GzFoa8AqULOhrZ6cfbDjrW0eUW_ZIxrCwB3xwIHvcA0bOWBE2MkIF_GG18wJv5lvUgKbSQJ7EOgRz5tn0vZPCA6NR7n0fKdhsDJOv3snAuzyDM_sluWs0sOtVKp9oNYox5L1FA7AH6Uvp6O7x2tchYez3fs4cNuoB271eWTScCo--wuLXXzhtYvJVF6Y5oEJ4tj71XgOIQ44Txuc8HYm8e8erygek3X0UP7I3uoe2Rf5YL_MnQ-8NADSX5-piVSiHne6ruJ5ydm__-smb1KhBAAA.DRVfJGOCwxTdkOaLFqGm0wrdEy-w9sSHUoqAY9aokHBh2lBLPLub19YbQQRKMwORKE2LU-OrD3GMDoFE3G-P1RqV0d6HFP2GcgH9UGPQv68qHfYiaUwnRkZilU9fyxqduxOOvUeYxSppmdD05wd2A4C4JNGuX0UeyaH1SXLBTAfevvXUzdgkOyuO3iy6vER8KwwT7ooTRLQRpEspUPd6uIbCFWtVTrXxaP13Xpo9xwd0LMMydSuqx6NL_lam5bIzAfSKXRdXP7i94Xj1cxmpvP8q1i-GkUKfing6zX41Ta_MDgfyzIvj18pqehAD6pB8pYfOdTzWbamBHzOiHptHoo-DdewuEHhwYRBfXVYEX5EM8fIWr58bLdJh-BTQuB-t5RrkfTb7M9bvir4fBsumrM2UY3iL_Xr0kj730GAioNXYgpmYPrRvgmQOY7bG52niBbz5avNBz6oZ_JRTMMONf-spPGHx68Qk1kI3d7W3PaYO9DNvDhqx_y0ZUhD9fj7U7iyFonQ-NcLnUeJ5ywC2yEwPW8edtrnHd6h6E1Sk9GTEYR5PI6tmTDbhSlW1wlXkj-qilHdIFPWVpXmLpx1BIpamxaKrURtzT9ztA7wIY-O55maNILjKLNK3O6F3Xiw8TnQ0mpELeBgp5KbIQLnX6X9Rc4hhAfqWJOuOQANVd9o
    accounts:
      listaccnums:
        verb: GET
        resource: /api/v2/accounts
      confirmationoffunds:
        verb: GET
        resource: /api/v2/accounts/{accountUid}/confirmation-of-funds
    transactionfeed:
      getsettledinrange:
        verb: GET
        resource: /api/v2/feed/account/{accountUid}/settled-transactions-between
    savingsgoals:
      get:
        verb: GET
        resource: /api/v2/account/{accountUid}/savings-goals
      create:
        verb: PUT
        resource: /api/v2/account/{accountUid}/savings-goals
      transfer:
        verb: PUT
        resource: /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}/add-money/{transferUid}