
outboundclients:
  starling:
    core:
      baseurl: https://api-sandbox.starlingbank.com
      accesstoken: eyJhbGciOiJQUzI1NiIsInppcCI6IkdaSVAifQ.H4sIAAAAAAAA_21Ty5KjMAz8lS3OoymeMXDb2_7AfoCw5MQ1YFO2yezU1v77mpiEkJob3S21JEv8zbT3WZ_hrIF4su8-oBu1OQ9oPt6lnbK3zC9DjChI8ansKhC5LKGmqoJWlBWoU1MLVmXTIMVg_jNnfSHypmjqou3eMo0hEflJiJVAKe1iwi87ErvfmjbvNlcnkKwQahQC2gZPgMR5M4iqGbiO3sF-sEkZncrrkomh7YYcalEM0HFRAKq8laWUbVl3MSOO9VNK9n6vUxaiBVIU66hKQVd0LRSipGFoquqUi3VgaWdeHyV1Cpdbq2Bw4t4x0o8XIXzNL4ImNkErze7Ij9qHA7MBIheb7Jl0eICkhIDyMvEjcgkX67SPGwJtSF81LTgmbcARjdw6kegIpDXB2TH5rsymWaO0mzBoa8AqUIuhrZ5cfLDTvW2eUG_ZExrCwD3xyIEf8BY2ccCIsJcRruId3zJn_GK-SwlsJgnsQaAnPG-eSds_ITg0HuXa84OG0co4_e6dCLDrM7yyW5azSo_3Uqn2gbpFOZas53AA_ih9Oh3dPV7jKjyc7d7HgdtGPXA3n2cmDafis39jsYvfeO1iMpUXpmVkgjj2fjWeQ4gDLvMGZ7yfSfzd4xXFY7KOnsof2XvdI_tNPthP8-ADrw2A9NdXaiaVqOed3lbxuuTs338rO4HroQQAAA.Q1xnlmcIpukS6M2uHlsE-js_8vWxZlpF2SZn5PcLVItHj6iRs041UswyuzdwOMdAkjUcv7VfyrwOEQ_jGfHakS4sdNaKE0RILR1j3Kbrt6hABk0D3AOTu_nzKBsVHVNOnD8x4mZYuC4YrLoerVei_6Fg9G0bVQLPTQmmfJeLHg5TG4qF0qRxanXydCnXvR7wFwy_GGkJo2sKDeSBT4d5Mni5FPLRDdceIr-d3NSyaD0ED6x61rjywt5QVE516YbFm4VPPBA1iXYcTvTb2If1rbycTIFOP1JptDOgW5BTLsR9Yh4lnZ41zfHvbp6wVMh6m-ZXaECuVDv91n3MzF1sX7s-YxjC7pWG8OsMEyICAZAaHOy0u89jPSSfSPfVYYf1pudSQhzDVYDV_L9yKXAVHhzhXdyZdhxnxEcW5-D0OI85SCVLOuNBRtYsy2yaG_cK0y9ww9EKnnkluc-K9LIATO2OhKQ0uH8Le7mLqOfq6BDFLfkCiehR9AfaynbkxZvCjOHPiJFNHdpfkAFmwtYr28TsURlcXIg6A7C3Q5QjHERzpsQ6ni19RogOVfIkyOn4KJpSQqKvYgMULE7S2UM8aAQ3xRU0NbqL2kPGiS7-fNed8JyAz6xaCXdMsmNH9XCc1OIgHRD3YqnhvJlfYKLsUuiqcmrlEtSqX4WhNhluujM
    accounts:
      listaccnums:
        verb: GET
        resource: /api/v2/accounts
      confirmationoffunds:
        verb: GET
        resource: /api/v2/accounts/{accountUid}/confirmation-of-funds
    transactionfeed:
      getsettledinrange:
        verb: GET
        resource: /api/v2/feed/account/{accountUid}/settled-transactions-between
    savingsgoals:
      get:
        verb: GET
        resource: /api/v2/account/{accountUid}/savings-goals
      create:
        verb: PUT
        resource: /api/v2/account/{accountUid}/savings-goals
      transfer:
        verb: PUT
        resource: /api/v2/account/{accountUid}/savings-goals/{savingsGoalUid}/add-money/{transferUid}